package ru.ifmo.sta.lab04.baev;

import java.util.List;

/**
* Generated by banler - Baev's ANother Tool for Language Recognition
*
* Saint Petersburg, 2013
* @author Dmitry Baev charlie@yandex-team.ru
*/
@SuppressWarnings({"all", "warnings", "unchecked", "unused", "cast"})
public class Node {
    private String name;
    private List<Node> children;

    public Node(String name, List<Node> children) {
        this.name = name;
        this.children = children;
    }

    public String getName() {
        return name;
    }

    public List<Node> getChildren() {
        return children;
    }
}
