package ru.ifmo.sta.lab04.baev;

import java.util.List;

/**
* Generated by banler - Baev's ANother Tool for Language Recognition
*
* Saint Petersburg, 2013
* @author Dmitry Baev charlie@yandex-team.ru
*/
@SuppressWarnings({"all", "warnings", "unchecked", "unused", "cast"})
public class SRuleNode extends Node {
    public int val;

    public SRuleNode(String name) {
        super(name);
    }

    public SRuleNode(String name, List<Node> children) {
        super(name, children);
    }

}
