package ru.ifmo.sta.lab04.baev;

/**
* Generated by banler - Baev's ANother Tool for Language Recognition
*
* Saint Petersburg, 2013
* @author Dmitry Baev charlie@yandex-team.ru
*/
@SuppressWarnings({"all", "warnings", "unchecked", "unused", "cast"})
public enum Token {
    PLUS,
    OPERAND,
    END
}
